# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Zee's Cyber Space"
title_zh: "子易赛博の空间"
author:
  name: Zee
  email: wangzee@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  A personal blog on things that Zee cared and still caring about.
description_zh: >-
  关于子易在意和仍在在意的事情的个人博客。

# Language settings
default_lang: en
languages: ["en", "zh"]
lang_names:
  en: "English"
  zh: "中文"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zeecares.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true # set to true to show excerpts on the homepage or false
# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  #skin: solarized
  date_format: "%b %-d, %Y"
#twitterusername: ZeeCares
#githubusername: zeecares
  # generate social links in footer
  social_links:
    twitter: ZeeCares
    github: zeecares
    # devto: jekyll
    # dribbble: jekyll
    facebook: apache.wang.5
    # flickr:   jekyll
    instagram: zeewang42
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    youtube_channel: UCnxBt9CHbVIMFySBl0AZ4Tg
    # youtube_channel_name: CloudCannon
    telegram: wanger1984
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# SEO Settings
seo:
  type: Person
  name: Zee
  links:
    - https://twitter.com/ZeeCares
    - https://github.com/zeecares
    - https://www.facebook.com/apache.wang.5
    - https://www.instagram.com/zeewang42
    - https://t.me/wanger1984

# Social media profiles for structured data
social:
  name: Zee
  links:
    - https://twitter.com/ZeeCares
    - https://github.com/zeecares
    - https://www.facebook.com/apache.wang.5
    - https://www.instagram.com/zeewang42

# Analytics
google_analytics: UA-167900064-1
google_site_verification: # Add your Google Search Console verification code here

# Related posts configuration
related_posts:
  enabled: true
  max_posts: 5
  fallback_enabled: true

# Default meta descriptions
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Zee
      image: /pic/circle.png # Default image for social sharing
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      author: Zee
      image: /pic/circle.png # Default image for social sharing

# Locale settings for better SEO
locale: en_US
timezone: Europe/Dublin

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
