# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 子易赛博の空间
email: wangzee@pm.me
description: >- # this means to ignore newlines until "baseurl:"
  Zee's personal blog. It may show the things that zee cared and caring about.
  /n子易的个人博客。它记录Zee曾在乎过或正在在乎的事情。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zeewang.ie" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ZeeCares
github_username:  zeecares

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
